### ISSUE TITLE
Modularize sprites/entities when using asset preloader event.

### ISSUE THREAD

**Issue by wini3d** [straker/kontra#100]
More on a question how to do this. I was trying to separate each sprite/entity on each separate js file and require them and then pack them all back in one later for production.

Also, will there be support for entity component system? maybe as a plugin.

**Comment by straker** [comment]
Kontra supports es6 modules, so you could `import` each separate entity into the file you need.

```js
import Player from 'entities/player.js';
import Enemy from 'entities/enemy.js';
// ...
```

You can then use a bundler like Rollup or Webpack to pack them all back together.

**Comment by wini3d** [comment]
I see, so something like just adding a script file then defining it as `window.player` would not work? 

I tried this on the tiled camera example, but getting a lot of errors.

**Comment by straker** [comment]
You'd have to probably manage the order that the script tags got loaded in so `window.player` was loaded before the tileMap, but it should work if you did globals as well.

```html
<script src="entities/player.js"></script>
<script src="entities/enemy.js"></script>
<script src="tileMap.js"></script>
```

**Comment by wini3d** [comment]
Thanks @straker, not really a big issue and figured the import method is a much cleaner or best approach. closing this for now.
