### ISSUE TITLE
onOver event only triggered when the pointer moved

### ISSUE THREAD

**Issue by Rayne** [straker/kontra#102]
The `onOver` event seems to be only called when the pointer was moved. I expected that the event is called every frame as long as the pointer is hovering above a `Sprite` because there is no "`onNoLongerOver`" event. Are there use cases for detecting pointer-`Sprite`-overlaps only once?

My workaround would be to use `pointerOver()` instead. Is this the intended solution?

**Comment by straker** [comment]
Yes the intended use is to use `pointerOver`. The `onOver` event is triggered for the browsers `mousemove` and `touchmove` events, so you only get the 1 event fired per move.

**Comment by Rayne** [comment]
Thanks for the clarification.
