### ISSUE TITLE
Multitouch support

### ISSUE THREAD

**Issue by Rayne** [straker/kontra#104]
Kontra doesn't support multitouch input. I am not talking about gestures. Is this out of scope or a valid feature request?

**Use Case**

- Scenario: Jump and run game

- Two sprites represent the "move left" and "move right" buttons

- Another sprite represents the "jump" button

- It is required that the combination ("move left" and "jump") or ("move right" and "jump") is detectable in one frame

**Comment by straker** [comment]
It's probably within the realm of possibilities. I'll have to investigate how to make it work
