### ISSUE TITLE
Separate fps

### ISSUE THREAD

**Issue by Ogimle** [straker/kontra#137]
for more flexible load control do two FPS options instead one
1 fps for render (load balancing)
2 fps for updating logic (accuracy balancing)
for example, because asteroids and adventures have different pc resource needs

**Comment by straker** [comment]
Sorry if I misunderstood, but do you mean have two different `fps` options in the `GameLoop`?

```js
const loop = kontra.GameLoop({
  renderFPS: 60,
  updateFPS: 30
});
``

**Comment by Ogimle** [comment]
yes

**Comment by Ogimle** [comment]
but..
const loop = kontra.GameLoop({
  renderFPS: 40,
  updateFPS: 60
});
for example with asteroids game, this setup dont impact on visualisation and help economy battery on mobile device

**Comment by frenzzy** [comment]
Why can't you throttle render function yourself?
```js
const renderFPS = 1000 / 40
let lastRender = 0
function render() {
  const now = perfomance.now()
  if (now - lastRender < renderFPS) return
  lastRender = now
  // ...
}
```
I mean what the point to have similar logic in the engine core if it is not a generic case?

**Comment by Ogimle** [comment]
This is a general case of optimization. When we need calculations at a speed of 60 frames per second, so that there are no problems with collisions and others, but at the same time relatively smooth graphics, we can separate the calculation and drawing processes.

**Comment by straker** [comment]
After thinking about this I agree with @frenzzy that this can already be done by throttling the render function yourself. There is no difference between @frenzzy code and what I would do inside the game loop, so you shouldn't lose any performance by self throttling.
