### ISSUE TITLE
tileEngine modifying 'sx' value directly freezes tileMap at '-768'

### ISSUE THREAD

**Issue by sdfereday** [straker/kontra#140]
Heyup,
I was just having a look at the following:
https://straker.github.io/kontra/api/tileEngine#addObject

As I'm looking in to tracking the camera to focus on the player as they move around the map. However when I implement the example above, it seems to make the tilemap stick at sx '-768' when I modify the value directly.

Am I missing something obvious?

Have a great christmas!

**Comment by straker** [comment]
Thanks for the Christmas wish. I'm looking at the example and unable to get it to get stuck when modifying the `sx` value of the TileEngine.

Just so I'm looking at the right thing, it's [this example](https://straker.github.io/kontra/api/tileEngine#adding-objects-to-the-tilemap) you're looking at yes?

**Comment by sdfereday** [comment]
@straker That's the right example yeah. However I think I've found the cause (still looking in to a solution) in that it's not actually the TileEngine but rather something to do with how I've set up the scaling on the canvas.

With it being a pixel style game I've directly edited the scaling so it zooms in more and I think that's affecting (visually at least) how the TileEngine works with the rest of it.

I'll keep looking in to it anyway and post back on here with any updates. Sorry for pointing fingers in the wrong place, seems it was my doing all along!

Cheers

**Comment by straker** [comment]
Glad you got it narrowed down. Let me know what you're doing with the scaling, I'm interested in what you're doing with it.

**Comment by sdfereday** [comment]
So at present with scaling I'm setting the size of the actual canvas element to give it a base resolution, then scaling everything inside it. I've got to be honest, not convinced this is the right way to go about it though...

```javascript
const resolution = {
   width: 1024,
   height: 576,
   scale: 4
 }

const { canvas } = init();

// Set canvas tag's physical size for the viewport
canvas.width = resolution.width;
canvas.height = resolution.height;

// Disable smoothing and scale up canvas context to enlarge rendered entities
const ctx = canvas.getContext("2d");
ctx.imageSmoothingEnabled = false;
ctx.scale(resolution.scale, resolution.scale); 
```

Trouble is it's the only way that I know of currently.
