### ISSUE TITLE
The word Sprite misspelled in docs

### ISSUE THREAD

**Issue by johanlindfors** [straker/kontra#148]
Minor spelling issue in the documentation for Pointer.

https://github.com/straker/kontra/blob/master/docs/api/pointer.html#L164

**Comment by straker** [comment]
Thanks for letting me know. Would you be interested in opening a pr to fix it? https://github.com/straker/kontra/blob/master/src/pointer.js#L41

**Comment by johanlindfors** [comment]
Done #149

**Comment by straker** [comment]
Closed via #149
