### ISSUE TITLE
Unable to import with parcel or webpack bundlers

### ISSUE THREAD

**Issue by andre-lima** [straker/kontra#15]
Hello,
I tried importing the package, after installing it from npm, with parcel and webpack but both didn't work.
Can you please clarify in the docs how we should proceed to make it work.
Thanks.

**Comment by andre-lima** [comment]
I forgot to mention, but I'm getting a ReferenceError: kontra is not defined.
The thing is that this is happening even when I import the kontra.js file directly from a script tag.

**Comment by straker** [comment]
How are you brining in the library through a script tag? I can understand it not working with webpack since it's not written in es6 module syntax (maybe that should be my next feature).

I ran `npm install kontra`, and then loaded it in an HTML file without problems.

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <script src="node_modules/kontra/kontra.js"></script>
  <canvas width="600" height="200"></canvas>
  <script>kontra.init();</script>
</body>
</html>
```

**Comment by andre-lima** [comment]
I managed to make it work with your example. 
But if i manually download the kontra.js file from your site, and try to import it in the index.html file in a **PARCEL** project, it doesn't work. This looks like an issue with how Parcel loads the scripts and tries to bundle them. 

I really would like to be able to use both together, if you have any idea on how to make it work, please let me know.

Thanks again.

**Comment by straker** [comment]
I am unfamiliar with parcel, does it work like webpack and require es6 module syntax to bundle imports?

**Comment by andre-lima** [comment]
Yes. But I now webpack has a way to import non-modules but I'm not too familiar with Parcel either. I just wanted to try it because it's very simple and because of this boilerplate: https://github.com/mtmckenna/js13kgames-parcel-starter .

**Comment by straker** [comment]
Kontra was originally written to be a loaded globally through a script tag, so it doesn't use any type of module loader syntax (CommonJS, Import, etc.). I'm not sure I have enough time to change it to use es6 module syntax before the jam starts in 12 days, but I can add it as a todo for next year.

**Comment by andre-lima** [comment]
That's cool. It would be cool if this gets done in the future. 
I'll keep an eye on it. Thanks.

**Comment by niicojs** [comment]
I wanted to give parcel + kontra a try also

**Comment by niicojs** [comment]
FYI, just modifying `this.kontra` by `kontra` in src/core.js seems to have fixed my error, but I'm still early in testing.

**Comment by niicojs** [comment]
Seems to work. I can make a PR if you have automated testing.

**Comment by straker** [comment]
Glad you got it to work. PR's are always welcome :)

**Comment by straker** [comment]
@andre-lima v4.0.1 should let you load Parcle thanks to @niicojs. Give it a try and let me know if it works for you.

**Comment by niicojs** [comment]
example on how I use it
![code](https://user-images.githubusercontent.com/5653050/44216895-66efbb00-a176-11e8-903e-b60144880a72.png)

**Comment by andre-lima** [comment]
Great. I'll test it once I get home.
Although, will it work with the npm package? It would be a lot more seamleas if we can just ```import kontra from 'kontra';```

**Comment by niicojs** [comment]
I'm using it from npm.
Might work directly with `import 'kontra'` but it's usually better to only import the module you are going to use in order to save some precious bytes.

**Comment by andre-lima** [comment]
Yep. It works importing with only `import 'kontra'`.
Thanks, guys.
