### ISSUE TITLE
Pointer not returning consistent x and y coords

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#150]
I'm using a Pixel 2 Emulated Android device. I have a sprite with an onDown function that uses pointer.x and pointer.y.
I'm clicking the sprite and logging out the x and y, and the numbers aren't consistent for the first few clicks. If I hold still and click the same spot, it'll be the same x and y after the second click.
The first click is always 0 0. It looks like the pointer is always one click behind.

**Comment by straker** [comment]
It could be because the pointer handler is always using the [last frames ordering instead of the current frame](https://github.com/straker/kontra/blob/master/src/pointer.js#L56-L61). This was to make sure of which object was truly on top instead of catching it in the middle of a render cycle.

**Comment by BoldBigflank** [comment]
This is v6.9.1, btw.

No, it's not one pixel off, it's the x/y of the previous click. Is the pointer object only updated on the click function?

**Comment by straker** [comment]
I think so. The pointer's x and y position only seem to be [updated after a touch event is fired](https://github.com/straker/kontra/blob/master/src/pointer.js#L217-L249), that may be the issue you're seeing. I would say that might be a bug if that's the case.

**Comment by BoldBigflank** [comment]
Yep that seems to be the issue, the pointer.x and pointer.y being set after calling the onDown for the sprite.

**Comment by BoldBigflank** [comment]
Weird that we don't see this issue for desktop browsers.

**Comment by BoldBigflank** [comment]
Actually, I'm still not following. The pointer is just fine at updating the sprite in its update function, and that's not being triggered by a pointer event, so pointer is getting updated every frame.

**Comment by straker** [comment]
The code path updates the pointer before the desktop click, but after the mobile touches. Most of the work for touch events was done in https://github.com/straker/kontra/pull/126 by @crhallberg

**Comment by BoldBigflank** [comment]
Oh yep, I see that now. Ok, I'll see if I can fix this up.

**Comment by crhallberg** [comment]
Thanks for the catch on this. Sorry I wasn't around to help!
