### ISSUE TITLE
Error when switching from one kontra canvas to another

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#152]
In Trivia Murder Party 2, there's two games that use Kontra. One is a Lotto Scratch Ticket, and the other is a Rotary Phone. When I load the Lotto Scratch Ticket (9 sprites with touch events), and then unload that and load the Rotary Phone (1 sprite with touch events and an animation, a couple other sprites) I get this error:

```
The index is not in the allowed range. - 
drawImage@[native code]
draw@https://jackbox.tv/2.988daa143fbae6dda4f4.js:1:11890
render@https://jackbox.tv/2.988daa143fbae6dda4f4.js:1:11209
forEach@[native code]
render@https://jackbox.tv/18.c4586627de4aaa17eb0e.js:1:13279
y@https://jackbox.tv/2.988daa143fbae6dda4f4.js:1:4617

```
These should have their own view, their own sprites array, their own gameLoops, so everything should not be in conflict but this error leads me to believe that's not the case. Here's my MarionetteJS onBeforeDestroy function:
```

onBeforeDestroy() {
        window.removeEventListener('resize', this.onResizeWithContext)
        const self = this
        for (let i = 0; i < self.sprites.length; i++) {
            self.sprites[i].ttl = 0 // reset
        }
        self.gameLoop.update(1 / 60)
        self.gameLoop.stop()
    },
    
```
Any hints on what might be causing this?

**Comment by BoldBigflank** [comment]
Oh, this error only happens on iOS devices (iPad and iPhone), but both Safari and Chrome.

**Comment by straker** [comment]
I have not heard of this error before, but looking at stackoverflow seems to suggest it happens when the x/y position is outside the canvas range? 

I would almost need a working test case to guess what is going on. However, I don't know if kontra is setup to handle multiple instances of itself on the same page.

**Comment by BoldBigflank** [comment]
You have a private form of communcation we could move this to? I can set you up with the test jackbox.tv credentials.

**Comment by straker** [comment]
My email steven at sklambert com

**Comment by BoldBigflank** [comment]
Looks like the underlying issue is the image of the sprite isn't loaded into the DOM yet, so the width/height of the image is 0. Safari doesn't like that. Would it be worth adding safeguards to the library to not render when the image width or height are 0?

**Comment by straker** [comment]
I guess it depends. Skipping the render cycle entirely may be confusing if you expect your sprite to render but it's not showing up. In a situation like this it would be more helpful if we told the user the problem rather than throwing that unhelpful error from Safari.

**Comment by BoldBigflank** [comment]
I think that in another use case where you _want_ the sprite to be 0px high for a frame. I would imagine just skipping the `drawImage` line would be fine.

**Comment by BoldBigflank** [comment]
oh, y'know what? I had fixed this in a previous version but didn't make a PR. Now that we've changed the way images are drawn we can remove the `0, 0, this.image.width, this.image.height,` line https://github.com/straker/kontra/blob/master/src/sprite.js#L633
This fixes the issue.
