### ISSUE TITLE
when initPointer is called twice, breaks pointerOver

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#155]
In Trivia Murder Party 2 you play a series of minigames. Since there's function to check whether the pointer is initialized, all the games will call `initPointer()`. The second game that gets played has some strange behavior and will not ever get pointerOver(this) in a sprite's update function to return true.

I think the fix for this is in `initPointer`, to remove any existing listeners and use `off()` to remove any existing 'tick' listeners.

**Comment by straker** [comment]
This should be fixed via #169. Let me know if that's not the case (also added support for passing the `canvas` to pointer if you need multiple canvas support for your two different games).
