### ISSUE TITLE
Kontra.js doesn't work on Internet Explorer 11 

### ISSUE THREAD

**Issue by rBok6** [straker/kontra#163]
I been trying to test kontra.js on Windows phone with Internet explorer 11 but none of the games or examples will load. Any ideas as to why? IE11 supports canvas and webgl.

**Comment by straker** [comment]
It's because kontra is written in [ES modules as of v6](https://github.com/straker/kontra/releases/tag/v6.0.0). You'll need to compile it using something like Rollup into non-es module code.

**Comment by rBok6** [comment]
Oh I see. Is such a pity 😢 Well thanks for letting me know.
