### ISSUE TITLE
Docs not styled when viewed offline locally

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#165]
I'm about to board a plane and am using the docs folder locally to develop. Currently it's missing styles.css because it's calling https://straker.github.io/kontra/assets/styles.css instead of a relative path.
There's also a couple other js files not being loaded, like kontra.js itself for the same reason.
I would expect the docs to be styled using the local copy of styles.css

**Comment by straker** [comment]
How are you loading them locally? I had to use a "hack" to get them to work both locally and on github pages, so I detect localhost and change the `<base>` tag. I could probably do it the other way around though so it defaults to local and only changes the base if on github.

**Comment by BoldBigflank** [comment]
To access them I was just loading the index.html file in the browser, no file serving stuff.

**Comment by straker** [comment]
Added a service worker to the docs so you can now view them offline. The pages are cached progressively so it will only cache what you have visited. I added an icon to indicate which pages are cached

<img width="335" alt="image" src="https://user-images.githubusercontent.com/2433219/92409937-a263d600-f0ff-11ea-97aa-899dd22e6ad8.png">
