### ISSUE TITLE
Passing the provided dt doesn't match the default dt

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#166]
When you pass the delta t in the update function of a Sprite, it causes the sprite to move at 1/60th the speed of a Sprite without a specific delta t. See the following code.

```
import {
    init, initKeys, keyPressed, Sprite, GameLoop
} from 'kontra'
import './style.scss'

const { canvas, context } = init()

let sprites = []

const sprite = Sprite({
    x: 100,
    y: 80,
    color: 'red',
    width: 20,
    height: 40,
    dx: 1,
    update(dt) {
        this.advance()
        if (this.x > this.context.canvas.width) {
            this.x = -this.width
        }
    }
})

sprites.push(sprite)

const sprite2 = Sprite({
    x: 100,
    y: 160,
    color: 'yellow',
    width: 20,
    height: 40,
    dx: 1,
    update(dt) {
        this.advance(dt)
        if (this.x > this.context.canvas.width) {
            this.x = -this.width
        }
    }
})

sprites.push(sprite2)

const loop = GameLoop({ // create the main game loop
    update(dt) { // update the game state
        sprites.forEach((sprite) => sprite.update(dt))
        sprites = sprites.filter((s) => s.isAlive())
    },
    render() { // render the game state
        sprites.forEach((sprite) => sprite.render())
    }
})

initKeys()
loop.start() // start the game

```

According to the docs, the optional `dt` parameter in the advance function is the same parameter in the update function, `Time since last update.`.

This has been the case for basically all of kontra's development, and it never felt right to me. I would expect the number being passed into the update function to be the right one to continue sending through to the advance function.

**Comment by straker** [comment]
The `dt` is used if you want to use time based movement, so you'll need to use `dx` and `dy` values that represent how far to move in 1 second rather than how far to move in 1 frame. In this case, `sprite2` should have a `dt` value of `60` rather than `1`.

**Comment by BoldBigflank** [comment]
So the two lines of thought are delta x per frame, and delta x per second, and they're only determined by the advance function's parameter is called?
Hmm, does that mean the documentation for Sprite.advance([dt]) needs to be updated? What the advance function receives is being multiplied, so would that be the `n frames` rather than delta t?

**Comment by straker** [comment]
It could probably use a bit more clarification. The advance function takes the `dt` value and uses it as a [scalar multiplier for the vector addition](https://github.com/straker/kontra/blob/main/src/sprite.js#L567-L568).
