### ISSUE TITLE
Suggestion: Some sort of extendable initialize function

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#173]
An `initialize` or an `onAwake` function that runs once when the sprite is instantiated would be great. What I currently do as a workaround is have some flag and set it in the update function

```
{
    initialized: false,
    update: function(dt) {
        if (!this.initialized) {
            // ... do setup work
            this.initialized = true
        }
    }
}
```

**Comment by straker** [comment]
Can your clarify your use case? Passing those properties into the object is initializing it so why can't you do the setup work then?

**Comment by BoldBigflank** [comment]
I'm just saying that my current method is sort of a hack, and it seems that this is somehow not guaranteed to be called before the first render function.

**Comment by straker** [comment]
That's what I'm trying to understand. The two use cases I see for needing to do additional initialize work are possible without needing a hack:

new class:

```
class myClass extends Sprite.class {
  init(props) {
    super.init(props);
    // ... do setup work
  }
}
```

and creation

```js
let sprite = Sprite();
// ... do setup work
```

**Comment by straker** [comment]
After thinking about this more I can't come up with a use-case for a function that is called on sprite initialize. From what I can imagine:

1) the initialize function is setting properties / state. if this is the case you can pass that state as props to the sprite when it is created
2) the initialize function needs to call an API to get its state. If this is the case I think an async function wrapper or a custom Sprite class would be better
 
```js
async function initSprite(props) {
   const state = await fetch(apiUrl).then(response =>  response.json());
  return Sprite({
    ...props,
   ...state,
  });
}
```

If you feel there's a use-case I'm missing please let me know. Going to close for now.

**Comment by BoldBigflank** [comment]
I think the reason I called for this was because I needed to wait for images to load before I could set everything up, and if the update/render functions were executing before that happened it would crash the website.
