### ISSUE TITLE
Suggestion: Create Sprite with extra properties

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#174]
Currently I do this:
```
const xView = Sprite(viewSprite)
xView.position.x = 256
xView.position.y = 256
```

What I would like to do is this:
```
const xView = Sprite(viewSprite, {
    x: 256,
    y: 256
})
```

**Comment by straker** [comment]
Would `const xView = Sprite(Object.assign({}, viewSprite, {x: 256, y: 256})` work for you?

**Comment by straker** [comment]
Going to close this as won't implement as destructuring the object is probably the cleanest solution:

```js
const xView = Sprite({
  ...viewSprite,
  x: 256,
  y: 256
});
```
