### ISSUE TITLE
PixelArt: image-rendering pixelated

### ISSUE THREAD

**Issue by daxrt** [straker/kontra#18]
How to display pixel art?

**Comment by daxrt** [comment]
How to display pixel art with canvas scale?

**Comment by straker** [comment]
Sorry, I'm not sure I understand the questions. 

If the pixel art is saved as an image, you can load the pixel art image and pass it as the `image` property to a sprite.

```js
kontra.assets.load('/path/to/pixel_art').then(() => {
  let sprite = kontra.sprite({
    image: kontra.assets.images['/path/to/pixel_art']
  });
});
```

What exactly do you mean by display the art with canvas scale?

**Comment by daxrt** [comment]
Sorry. I meant that I can not change the size of the image. My image is 16x16 pixels in size. In the game it seems small. I perform these manipulations https://gist.github.com/pixelpicosean/10622462, but it does not work in chrome

**Comment by daxrt** [comment]
```
context.mozImageSmoothingEnabled = false;  // firefox
context.imageSmoothingEnabled = false;
context.scale(5, 5);
```

**Comment by straker** [comment]
Nice! I'm glad you found an answer. Sorry I wasn't able to help.

**Comment by straker** [comment]
You can `context.save()` right before you apply the image smoothing and scaling and then `context.restore()` it afterwards to have it affect a specific image draw.

**Comment by candelibas** [comment]
Thanks a bunch! Made it work :)
