### ISSUE TITLE
Suggestion: Freeze render output

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#181]
I am thinking of doing some pretty math heavy render functions for GameObjects, but the draw won't change very often, like only onDown. It would be nice to say to use the previous frame's output rather than execute the render function every frame.  My example use case is a color wheel, where I'm setting each individual pixel just once, then not changing it again until I click it.

I understand that you're drawing straight to the canvas currently and it'll probably take a bit of refactoring.

**Comment by straker** [comment]
For the default GameObjects and Sprites, which use either rects or images, there is no need to cache the rendered output. Creating a custom `render` function on your GameObjects is probably the best way to implement this. That way you can control when the render function is called (when the object is considered dirty) and even implement drawing to an offscreen canvas to cache the rendered output if desired.
