### ISSUE TITLE
Docs do not match main branch

### ISSUE THREAD

**Issue by hfitzwater** [straker/kontra#185]
It looks like the docs located [here](https://straker.github.io/kontra/) are out of sync. The build docs action has been failing for awhile.

**Comment by straker** [comment]
I'm not sure I understand. The docs [Travis.org task pushed successfully to gh-pages](https://travis-ci.org/github/straker/kontra/builds/720409866). [The last commit with docs](https://github.com/straker/kontra/commit/fe843d3fb7c57ded8dfa48fa748977a40bf4b74c0 is [currently deployed](https://straker.github.io/kontra/api/button).

**Comment by straker** [comment]
Closing as the docs seem to be in sync. Please let me know otherwise.
