### ISSUE TITLE
kontra + parcel + typescript problem

### ISSUE THREAD

**Issue by ByteDecoder** [straker/kontra#186]
Hi, I have trouble, using kontra + parcel works fine for me and installing kontra with yarn. I can run with no problem with this snippet. 

`
import { init } from "kontra";

let { canvas, context } = init();
`

The problem starts when I try to add typescript. I can see the type definitions for kontra inside VSCode. When I run the same code using typescript I always get this error:  **Uncaught TypeError: (0 , _kontra.init) is not a function**

I think the problem is my configuration in the tsconfig.json file, but I cannot find in the documentation a way to configure typescript with kontra.

This is my current tsconfig.json

`
{
  "compilerOptions": {
    "moduleResolution": "node",
    "baseUrl": "./src/js",
    "paths": {
      "~/*": ["./*"]
    },
    "noImplicitAny": false,
    "module": "es6",
    "target": "es6",
    "noEmit": true,
    "allowJs": true,
    "sourceMap": true,
    "lib": ["es6", "dom"],
    /* List of folders to include type definitions from */
    "typeRoots": ["node_modules/@types"],
    "esModuleInterop": true
  },
  "include": ["src/js/**/*"]
}
`

Could you point me in the right direction to configure kontra with typescript?

**Comment by straker** [comment]
I'm actually not very familiar with TypeScript myself. I just run the default `tsc` compiler and it works. More than that I've not used it myself very often. I'll see if I can find someone more familiar to help out.

**Comment by ByteDecoder** [comment]
Hi, I was digging since yesterday with this. So I clean the tsconfig.json file and just add the next settings and everything works well.

`{
  "compilerOptions": {
    "baseUrl": "./src/js",
    "paths": {
      "~*": ["./*"]
    }
  },
  "include": ["src/js/**/*"]
}`

I created gist, with all files for setup kontra with Parcel, ESLint, Prettier, and Typescript with the example code from the documentation, in case someone wants to use that combination.

[https://gist.github.com/ByteDecoder/e70a62b6a1849ca2e1d79b3fe2b9fff2](url)
