### ISSUE TITLE
Unable to bind to Backspace or Delete keys

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#187]
I looked a little at the callbacks[key] stuff and couldn't figure out how an unnamed key like 'w' would work but am probably just going to work around it for the time being.

**Comment by straker** [comment]
The [keyMap](https://straker.github.io/kontra/api/keyboard#keyMap) should allow you to add more keys using the KeyboardEvent.code value. So adding `kontra.keyMap['Backspace'] = 'backspace'` should then let you detect/bind when `backspace` is pressed

**Comment by straker** [comment]
Did the `keyMap` work for you?

**Comment by straker** [comment]
Closing as `keyMap` should be the way to do this.
