### ISSUE TITLE
[Suggestion] Allow Scene's children property to work with Arrays

### ISSUE THREAD

**Issue by Andrek25** [straker/kontra#191]
Something like this:

```
sprites = [player, enemy1, enemy2, enemy3, ...]
scene = Scene({
	id: 'game',
	children: [tileEngine, sprites],
	cullObjects: false
})
```

**Comment by FTOH** [comment]
You can use [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) or [concat method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)
```js
console.log([tileEngine, ...sprites])
console.log([tileEngine].concat(sprites))
console.log(sprites.concat(tileEngine, anotherSprite, ...))
```

**Comment by Andrek25** [comment]
Thanks! i'm learning Javascript but i really don't know why i didn't think that.
