### ISSUE TITLE
[Bug] SpriteSheet clone is not a function.

### ISSUE THREAD

**Issue by Andrek25** [straker/kontra#192]
I'm using [Tiled Edit](https://www.mapeditor.org/) and make a Objects layer to use Insert Tile for drawing some specials tiles(doors, pushable boxes, etc) so i trying to draw them like this:

```
class Box extends Sprite.class {
	constructor(object) { // object => Tiled Editor object.
		let props = {
			name: 'Box',
			x: object.x,
			y: object.y,
			animations: Animation({
				spriteSheet: SpriteSheet({
					image: imageAssets['img/tileset'],
					frameWidth: 16,
					frameHeight: 16
				}),
				frames: parseInt(object.gid) - firstgid
			})
		}
		super(props)
	}
}
```
But i'm getting this error: Uncaught TypeError: value[prop].clone is not a function [kontra.js:2322](https://github.com/straker/kontra/blob/main/src/sprite.js#L102)

**Comment by straker** [comment]
It looks like the problem might be that `Sprite.animations` is not a Animation object but a [SpriteSheet.animations object](https://straker.github.io/kontra/api/sprite#animation-sprite.).

Also, you [don't typically use Animation directly](https://straker.github.io/kontra/api/animation), but rather create it using the SpriteSheet object.

```js
animations: SpriteSheet({
    image: imageAssets['img/tileset'],
    frameWidth: 16,
    frameHeight: 16
    animations: {
      // create a named animation: walk
      walk: {
        frames: parseInt(object.gid) - firstgid,
        frameRate: 30
      }
    }
  });
```

**Comment by Andrek25** [comment]
Nice thanks :), but `frames: parseInt(object.gid) - firstgid,` does not works for me, i need to use Array `frames: [parseInt(object.gid) - firstgid],`.

Is there a way to set an image's offset?

Example:
```
class Box extends Sprite.class {
	constructor(object) { // object => Tiled Editor object.
		let gid = parseInt(object.gid) - firstgid
		let props = {
			name: 'Box',
			x: object.x,
			y: object.y,
			image: imageAssets['img/tileset'],
			imageOffsetX: gid % TILE_WIDTH * TILE_SIZE,
			imageOffsetY: gid / TILE_WIDTH * TILE_SIZE
		}
		super(props)
	}
}
```

**Comment by straker** [comment]
Currently no, only margin is supported.
