### ISSUE TITLE
Best way to flip sprites after update

### ISSUE THREAD

**Issue by sdfereday** [straker/kontra#194]
Hey all,
I noticed that the old method of flipping a sprite (by setting width to negative) has been removed recently. Is there a new and better way of doing this? I've been getting mostly correct results by setting the scale to negative across the x axis, however the sprite appears to jump when it's flipped. Is this something to do with the anchor or am I missing a better solution?

Cheers!

**Comment by sdfereday** [comment]
Apologies, it seems that the problem did indeed exist with the anchor being incorrectly set. The sprite now flips successfully using the 'setScale' method. I'll leave this open for now in case there's a more correct solution to this one.

Ta!

**Comment by straker** [comment]
No problem. Anchor + the `setScale` method is now the correct way to flip sprites.

**Comment by sdfereday** [comment]
Thanks for confirming @straker, much appreciated :)
