### ISSUE TITLE
Suggestion - "Headless" mode

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#200]
I know that there's a lot in Kontra's library about rendering to canvas. I had an idea about using Kontra's GameLoop and Sprite classes, but leaving the rendering to BabylonJS. I would modify the Sprite class to have an associated mesh, but basically the render function wouldn't be necessary. I'm certain I could do this as-is with a throwaway canvas, but it would be a little cleaner if I could get those out of there.

**Comment by BoldBigflank** [comment]
This would also be useful for a server/client type thing, where the server is running the game state and clients would need to get the state of the game from it.

**Comment by straker** [comment]
So would that just be having the Sprite/GameObject class but without the `render` and `draw` functions?

**Comment by straker** [comment]
@BoldBigflank I'm looking into this one again. Could you provide an example of what you would expect the headless mode to look like on the client / server (just pseudo code is fine)?  That would  help me figure out what it would take to support this.

**Comment by BoldBigflank** [comment]
My original desire was so that I could take a simple game that I created (such as https://alexswan.info/kontra-samples/plinko) and instead of each sprite drawing on a canvas, updating the position of a 3d model in an three.js scene. The update function would be the same, but rendering would involve code that didn't directly paint onto a canvas element.

**Comment by straker** [comment]
How would you envision that working? Would the `render` and `draw` functions noop'ing be sufficient?

**Comment by BoldBigflank** [comment]
It's been a while but I believe the first hangup is the init function requires a canvas to work. There might still be a render function, since I would still need to get my tracked Sprite visible on the threejs canvas. It would probably need to make sure that the default draw() doesn't happen ever though.

**Comment by straker** [comment]
Alright, new pr should allow this. Tested with the following code:

```js
kontra.init(null, { contextless: true });

// Find the latest version by visiting https://cdn.skypack.dev/three.
import * as THREE from 'https://cdn.skypack.dev/three';

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
const renderer = new THREE.WebGLRenderer();
const geometry = new THREE.BoxGeometry();
const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
const cube = new THREE.Mesh( geometry, material );

scene.add( cube );
renderer.setSize( window.innerWidth, window.innerHeight );
camera.position.z = 5;
document.body.appendChild( renderer.domElement );

const sprite = kontra.Sprite({
  update() {
    cube.position.x += 0.01;
    cube.position.y += 0.01;
  },
  render() {
    renderer.render( scene, camera );
  }
});

const loop = kontra.GameLoop({
  clearCanvas: false,
  update() {
    sprite.update();
  },
  render() {
    sprite.render();
  }
});
loop.start();
```
