### ISSUE TITLE
Animation loading problem

### ISSUE THREAD

**Issue by joseasv** [straker/kontra#202]
Hello. I used Kontra for my first game in the js13k competition of this year (https://js13kgames.com/entries/lost-pages). All worked as expected but not the animations. If you load the game for the first time all animations doesn't load. If you reload the game all animations work. 

I suppose this for the fact that I used a number of off screen canvases to create flipped sprites for flipped animations but I'm not so sure.

**Comment by straker** [comment]
Alright, I think I have figured out the problem. When you load the spritesheet the final time you use [getImageData and set it as the src](https://github.com/joseasv/js13k-lostpages/blob/master/src/index.js#L226). This operation is not synchronous and still [requires that canvas to load the image](https://github.com/straker/kontra/issues/195#issuecomment-687798997).

To fix the problem, you just need to add an `onload` event to the `ssheetImage` image and then create everything inside of that.

**Comment by joseasv** [comment]
Thanks. To not mess with the code that much [I added a busy-wait with setInterval](https://github.com/joseasv/js13k-lostpages/blob/c037b4370c2a53d9a86383d18294758b40c8b279/src/index.js#L1218) that waits for all Images to load.

Now the game shows all animations in the first load https://joseasv.github.io/js13k-lostpages/.
