### ISSUE TITLE
Question: Gravity and collision test when using TileEngine

### ISSUE THREAD

**Issue by mandyedi** [straker/kontra#203]
Hi,
I would like to implement a basic platform game physics with gravity. The main concept is that I use a TileEngine with a layer that is used in a collision test (layerCollidesWith) with the player Sprite.
The problem is, that whenever the Sprite collides with a layer, it passes the tile's border.
![collision_fails](https://user-images.githubusercontent.com/1611288/98514547-e68f6600-2269-11eb-9ed6-7532eec0ed5a.png)

Here is my implementation. Based on the Kontra documentation I was thinking that I can use the ddy for the gravity, and whenever the player collides with the ground, I set dy and ddy to zero. What is your recommendation to implement gravity?
Of course, I want to add jumping too, so it could give the player a negative velocity that would be decreased over time then the gravity would take effect again.

```js
let player = kontra.Sprite({
    x: 100,
    y: 350,
    width: 60,
    height: 84,
    dx: 0,
    dy: 0,
    ddx: 0,
    ddy: 2,
    anchor: {x: 0.5, y: 0.5 },

    update() {
        if (tileEngine.layerCollidesWith('groundLayer', player) === true) {
            dy = 0;
            ddy = 0;
        }
        this.advance();
    }
});

let loop = GameLoop({
    update: function(dt) {
        player.update();
    },
    render: function() {
        tileEngine.render();
        player.render();
    }
});

loop.start();
```

**Comment by straker** [comment]
Interesting. I'll have a look at this later today. As for gravity, I don't particularly have a recommendation for it but I think `ddy` should work fine, https://codeincomplete.com/articles/tiny-platformer/ does something similar and the affect feels nice.

**Comment by mandyedi** [comment]
Thank you, I'll have look at the link you suggested. I also delved into the subject and I think I simplified it a little bit and more details need to be considered.

**Comment by mandyedi** [comment]
When the collision test happens the player already passed the tile border. We can subtract the last dy or just clamp the position to the border of the collided tile. The link you suggested is a great example if anyone would struggle with this too. This is also a good tutorial: https://www.raywenderlich.com/2554-sprite-kit-tutorial-how-to-make-a-platform-game-like-super-mario-brothers-part-1
