### ISSUE TITLE
Create new release with keyup handler in bindKeys

### ISSUE THREAD

**Issue by johnedvard** [straker/kontra#219]
Hello, and thanks for a wonderful library.

I tried to use the `bindKeys` function, and pass `keyup` as the handler, but it was always triggered on `keydown`.
I had a look at the latest release [v7.1.2](https://github.com/straker/kontra/releases/tag/v7.1.2), and I noticed that the bindKeys function inside `keyboard.js` has not been updated. It still looks like this:

```
export function bindKeys(keys, callback) {
  // smaller than doing `Array.isArray(keys) ? keys : [keys]`
  [].concat(keys).map(key => callbacks[key] = callback);
}
```

Is it possible to create a new release and publish it to npm with the update?
Cheers~

**Comment by straker** [comment]
Sorry about that! You are correct. I'll get a release out shortly.

**Comment by straker** [comment]
Alright, took a bit longer than I hoped but [v7.1.3 is released](https://github.com/straker/kontra/releases/tag/v7.1.3).
