### ISSUE TITLE
Investigate allowing esbuild to tree shake library

### ISSUE THREAD

**Issue by straker** [straker/kontra#237]
I discovered that esbuild does not tree shake the library at all (https://github.com/evanw/esbuild/issues/1573). The issue might be in the way each of the classes assigns `class` and `prototype` for the factory function. Need to investigate changing this.

```js
export default function factory() {
  return new Vector(...arguments);
}
factory.prototype = Vector.prototype;
factory.class = Vector;
```

**Comment by straker** [comment]
Confirmed that it is both the factory assignment and any class that extends the `.class` property. Once those are both removed, esbuild tree shakes properly.

```js
class Text extends GameObject.class 
```

**Comment by straker** [comment]
Also need to add `/*@__PURE__*/` to any assignment to `WeakMap()`. It's apparently not listed as [a known global in esbuild](https://github.com/evanw/esbuild/blob/f50aa9a1a71a7db80adb6ec34896a98e32ed927a/internal/config/globals.go#L15-L24).

```js
let pointers = /*@__PURE__*/new WeakMap();
```

**Comment by anderoonies** [comment]
I'm interested in taking a look at this, but think I'm missing some context for the constraints here.
I'm assuming the API needs to stay consistent, so the default export needs to function the same, but is there any constraint on additional exports from these modules? Exporting the class in addition to the default factory can prevent the `extends Module.class`

Thanks for helping!

**Comment by straker** [comment]
Thanks! 

Since this is going to be a breaking change (there's no way to remove the `.class` assignment without it being breaking) the only constraints are that the factory export can't change (I want to make sure you don't have to call `new` for everything) and the class itself is exported in some way so that the user can extend it.

**Comment by anderoonies** [comment]
it looks like switching the `.prototype` assignments to use [`Object.setPrototypeOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) and marking them as `/*#__PURE__*/` allows for them to be eliminated:

```js
// lib.js
export function one() {
    console.log("one");
}
export function two() {
    console.log("two");
}

/*#__PURE__*/ Object.setPrototypeOf(two, "x");
```

```js
// input.js
import * as lib from './lib.js'
lib.one()
```

```js
// out.js
(() => {
  // ../treeshaketest/lib.js
  function one() {
    console.log("one");
  }

  // ../treeshaketest/input.js
  one();
})();
```

so i think the combination of using `setPrototypeOf` and exporting the classes separately would allow for dead-code elimination

**Comment by straker** [comment]
Oh nice. Though I don't remember exactly what the purpose of the setting the prototype was. I think originally it was so you could extend it for functional extends (e.g. `function CustomSprite () {} CustomSprite.prorotype = Sprite.prototype`). It may not be needed at all anymore now that I switched to classes.

**Comment by anderoonies** [comment]
It looks like I was actually wrong as well, after doing some more testing it looks like marking the `setPrototypeOf` as `PURE` will completely remove the prototype assignment from the bundle. But if that's not needed that simplifies things

**Comment by anderoonies** [comment]
i believe i have esbuild treeshaking working properly and all tests passing:
```
> npx rollup game.js --format iife --file rollup.out.js 
> npx esbuild game.js --bundle --format=iife --outfile=esbuild.out.js   
> ls -lah *out.js
35K esbuild.out.js
52K rollup.out.js
```

i followed through with what was discussed, and exports are:
```js
export default function factory() {
    return new Text(...arguments);
}
export { Text as TextClass };
```

etc.

before i make a pull request i want to confirm i have code formatted properly, is there a CLI for code formatting for this project?

**Comment by straker** [comment]
Unfortunately there is not. I've been meaning to set one up but haven't done so. Code formatting is mostly just 2 spaces instead of tabs at this point.
