### ISSUE TITLE
Disable button on creation

### ISSUE THREAD

**Issue by straker** [straker/kontra#241]
Should be able to create a button in a disabled state.

```js
Button({
  disabled: true
});
```

**Comment by alfi-s** [comment]
Hi there! Do you mind if I try my hand at this issue? I've never contributed to open source before and this looks like a straightforward issue.

It seems to me like the functionality for a disabled button is already there, and it's a matter of adding this option to the initialization properties.

**Comment by straker** [comment]
Sounds great! Please be sure to also a test to https://github.com/straker/kontra/blob/main/test/unit/button.spec.js as well.

**Comment by alfi-s** [comment]
Thanks, this issue should already be addressed in PR #243 now!
