### ISSUE TITLE
Prevent default behavior with keypresses

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#25]
Is it possible to do event.preventDefault() with keypress bindings? For example, hitting the space bar in my game will do a thing, but also scroll down the window a page.

**Comment by straker** [comment]
Yep, though I released I didn't put in the docs. Each `kontra.keys.bind` function callback is passed the original `Event`, so you can preventDefault there.

```js
kontra.keys.bind('space', e => {
  e.preventDefault();
});
```

**Comment by BoldBigflank** [comment]
You're right, tried it out and worked like a charm.

**Comment by straker** [comment]
I'll leave this open to remind me to add it to the docs. Thanks for asking!
