### ISSUE TITLE
Multi-touch Support for Pinch and Zoom

### ISSUE THREAD

**Issue by davesides3** [straker/kontra#258]
This may be a duplicate of the gesture feature request (https://github.com/straker/kontra/issues/209#issue-775072258), but it would be great to have a way to do pinch and zoom on mobile. I've been able to get panning with touch drag to work, but I think detecting multi-touch is going to require some mods to Kontra? Thanks.

**Comment by straker** [comment]
Thanks for the suggestion. I'll see what it'll take to implement more than just swipe for touch gestures.

**Comment by davesides3** [comment]
This is great! I'll try it out this weekend. Thank you!

**Comment by straker** [comment]
Awesome. Hopefully it works out. I expect there might be a few bugs with a new feature so let me know if you find any :)
