### ISSUE TITLE
Unable to use tilesets with margins

### ISSUE THREAD

**Issue by triptych** [straker/kontra#27]
Some tilesets like https://kenney.nl/assets/roguelike-caves-dungeons have margins - there's no way to define a margin in kontra so that prevents one from using those tilesets without manually editing them to remove the margins.

**Comment by straker** [comment]
You are correct. I thought I had implemented margins but it seems I only did it for spritesheets. 

I won't be able to add this feature before the end of the js13k competition, but will get on it afterwards.

**Comment by triptych** [comment]
Thanks!

**Comment by straker** [comment]
Quick question: will removing `tileEngine.addLayer()` or `tileEngine.addTileset()` be a problem for itty-bitty-rpg?
