### ISSUE TITLE
Assets load() function doesn't work with Array values

### ISSUE THREAD

**Issue by AlphaT7** [straker/kontra#272]
Per the user guide: [https://straker.github.io/kontra/api/assets](url) it seems to indicate that arrays are a valid input value for the `load()` function. But it errors out every time I try to use an array value for parameter, i.e.: `load(array).then().....`

The error is: 

`main-module.js:768 TypeError: url.replace is not a function
    at joinPath (kontra-module.js:374)
    at kontra-module.js:583
    at new Promise (<anonymous>)
    at loadImage (kontra-module.js:580)
    at kontra-module.js:765
    at Array.map (<anonymous>)
    at Module.load (kontra-module.js:760)`

If I hand feed it the file names, example: `load("img1.png","text1.txt","audio1.wav").then()...` with the same data it works as expected.

**Comment by straker** [comment]
That is correct. The [laod](https://straker.github.io/kontra/api/assets#load) function takes a list of strings and not an array. It does accept an array for audio type files to support multiple audio types based on browser support.

> Parameters
>
> `...urls`
>
>    A list of Strings. Comma separated list of asset urls to load.
