### ISSUE TITLE
Find a way to purge local storage when docs are updated 

### ISSUE THREAD

**Issue by johnedvard** [straker/kontra#289]
I used Kontra from version 7. Kontra caches the docs to localStorage when you visit a page. After version 8 was released, I still see the old docs (because of the cache). After deleting the localStorage under `https://straker.github.io/` I was able to get the latest docs. 

I happen to notice this after `bindKeys` didn't work anymore.

**Comment by straker** [comment]
That's a good point. The docs have a service worker that fetches the latest content and will update for you after you navigate to it and refresh/close the page. But there is that first time that means you have out-of-date docs. I'll try to implement a "There's a newer version of this page" type of notification so you're informed of the changes.
