### ISSUE TITLE
Please add my game to "Games made with Kontra"

### ISSUE THREAD

**Issue by johnedvard** [straker/kontra#290]
I love kontra. I created a game during js13kgames 2021 with it: https://js13kgames.com/entries/kurve-space.

Please let me know if it's worthy of a spot in your "game of fame" section https://straker.github.io/kontra/made-with-kontra ☺️

**Comment by straker** [comment]
Of course! Feel free to open a pr to add it or I can do it later today.

**Comment by straker** [comment]
Added https://straker.github.io/kontra/made-with-kontra (might need to refresh the page to get the latest version).
