### ISSUE TITLE
Investiate Pointer and Scene.lookAt issues

### ISSUE THREAD

**Issue by straker** [straker/kontra#294]
I think I completely missed testing out pointer events with objects in a Scene that uses the `lookAt` function. Need to do some investigating.

**Comment by straker** [comment]
Also investigate pointer events with objects in a TileEngine that uses camera.

**Comment by straker** [comment]
Confirmed that this is a problem. Seems removing all the GameObject camera code also made it so pointer events can't work on Scene and TileEngine (since they are now controlling the "camera").

**Comment by blakeearth** [comment]
Could this cause pointer events to not work with objects that have y-values less than zero?

**Comment by straker** [comment]
Update on this ticket. This issue has been tricky to resolve since both Scene and TileEngine are affected, but both in different ways. The main problem is when a Scene contains a TileEngine, which cause the problem to be twice as bad.

I've been trying different approaches to try to resolve, but nothings has worked nicely yet. Will continue to work on it to get it into the v9 release.

**Comment by blakeearth** [comment]
I appreciate this update. My project did have a TileEngine inside a Scene.

I'm working on a different project now that uses TileEngine for camera and pointer features and does not mix them.

**Comment by blakeearth** [comment]
Awesome!!!
