### ISSUE TITLE
Add Cowork to Made With Kontra?

### ISSUE THREAD

**Issue by blakeearth** [straker/kontra#297]
I'm making [Cowork](https://joincowork.com), a gamified productivity software via Innkeeper Games. The "game" portion of it is made with Kontra, which has been perfect for this project! It's lightweight, accessible, and a breeze to build with.

Here is an image: https://i.snap.as/fH3xL7iw.png

I would love to add it here, but I understand if it's not a great fit.  It's just now starting to enter "alpha" testing, so it's not done, and the source code is private (at least for now).

Thanks for developing and maintaining this awesome software! You're enabling the creation of a bunch of cool things, too.

**Comment by straker** [comment]
That's a good question. I'd say as long as it follows the [[CODE_OF_CONDUCT.md](https://github.com/straker/kontra/blob/main/CODE_OF_CONDUCT.md) guidelines I don't see any reason why it shouldn't be added.

**Comment by blakeearth** [comment]
Thank you. I am working on making some changes, including making the software open source. I will re-open this when Cowork is ready for an open-source release and submit a PR then.
