### ISSUE TITLE
Can't load Tiled map that uses tilesets as jsons

### ISSUE THREAD

**Issue by darkwebdev** [straker/kontra#30]
map created by Tiled uses the following structure:

```
...
"tilesets":[
        {
         "firstgid":1,
         "source":"tileset.json"
        }
],
...
```
Kontra expects the image inside tileset, but not json:
https://github.com/straker/kontra/blob/master/src/tileEngine.js#L190
```
addTilesets: function addTilesets(tilesets) {
  [].concat(tilesets).map(function(tileset) {
    let tilesetImage = tileset.image;
...
    image = tilesetImage;
...
numTiles = ( (image.width / tileWidth | 0) || 1 )
```

the last line throws a runtime error of course:
`Uncaught (in promise) TypeError: Cannot read property 'width' of undefined`

**Comment by straker** [comment]
Thanks for the issue. 

How do you export a json file with a json source for the tileset? I've never done it before.

**Comment by darkwebdev** [comment]
@straker hey, actually [in the Tiled docs](http://docs.mapeditor.org/en/stable/manual/editing-tilesets/) it says 

> A tileset can be either embedded in a map file or saved externally. Since Tiled 1.0, the default and recommended approach is to save your tilesets to their own file. This simplifies your workflow since it makes sure any meta-information is shared between all maps using the same tileset.

So there are two ways to create a tileset. Embedded way (you just click "OK" button at the end):
<img width="424" alt="image" src="https://user-images.githubusercontent.com/2737310/45633544-5649a200-baa0-11e8-82d4-58190851591b.png">

and separate file way (you click "Save as" button and save as .json/.tsx/.xml):
<img width="423" alt="image" src="https://user-images.githubusercontent.com/2737310/45633527-4a5de000-baa0-11e8-9501-54583ae39750.png">

`tileset.json` structure:
```
{ "columns":8,
 "image":"tileset.png",
 "imageheight":1450,
 "imagewidth":256,
 "margin":0,
 "name":"tileset",
 "spacing":0,
 "terrains":[
        {
         "name":"Stone road",
         "tile":1
        }],
 "tilecount":360,
 "tileheight":32,
 "tiles":
    {
     "0":
        {
         "terrain":[1, 1, 1, 1]
        },
     "1":
        {
         "terrain":[0, 0, 0, 0]
        }
    },
 "tilewidth":32,
 "type":"tileset"
}
```

**Comment by straker** [comment]
So that lets me save the tileset as a `.json` or as a `.tsx` file, but how do I get that file to be the `source` property of a `tileset` object (sorry, the new version is very new to me)? I'm not finding a property called `source` [in the docs for tilesets](http://docs.mapeditor.org/en/stable/reference/json-map-format/#tileset).

**Comment by darkwebdev** [comment]
Are you sure? How Tiled embedds the tilesets in the map is a bit awkward sometimes, so for the clarity of the experiment I'd suggest to create a new map and a new tileset and not to have any other tabs open inside Tiled. I've just recreated a new map, a new tileset, then put one tile on the map and saved it. That got me a map file with:
```
...
"tilesets":[
        {
         "firstgid":1,
         "source":"tileset.json"
        }
]
...
```

**Comment by straker** [comment]
So I'm still not having any luck producing this (tried the only tileset open). Could you go through step by step how you're doing this  for me?
