### ISSUE TITLE
Pointer/Touch events not working

### ISSUE THREAD

**Issue by lynxaegon** [straker/kontra#31]
I'm trying to do a simple touch / click at first, but it seems that the events are not fired. I also tried on mobile, and sometimes it fired an alert for the onDown function, but not always.

```
this._kontra.card = kontra.sprite({
	x: 0,
	y: 0,
	image: KontraSprites.card,
	width: this.width,
	height: this.height,
	onDown: function() {
		console.log("down");
	},
	onUp: function() {
		console.log("up");
	},
	onOver: function() {
		console.log("over");
	}
});

kontra.pointer.track(this._kontra.card);
```

And I have a really simple gameLoop:
```
kontra._loop = kontra.gameLoop({
	update: function() {
		sprite.update();
		for(var i in KontraPOOL){
			KontraPOOL[i].update();
		}
	},
	render: function() {
		sprite.render();
		for(var i in KontraPOOL){
			KontraPOOL[i].render();
		}
	}
});

kontra._loop.start();
```

Any ideas why the events for the pointer won't fire? Am i missing something?
Thanks

**Comment by straker** [comment]
Ah right. I almost forgot I had a bug I needed to fix in the pointer code. I forgot to account for canvas offset and scale. 

I [wrote the fix in my js13k game](https://github.com/straker/js13k-2018/blob/master/src/input.js#L49-L61) but need to transfer it over. Thanks for the reminder.

**Comment by lynxaegon** [comment]
Hmm, yeah that makes sense :) I didn't even realize that i was on a scaled canvas until you said it.

**Comment by lynxaegon** [comment]
I forked the repo and added your fix for scaling and offset, but after that i found out that i wasn't waiting for the images to load, and when i created the sprites, they had 0 width and height, the image was showing correctly, but when checking for input it couldn't create a bounding box. 

Now i'm waiting for the images to load, and after that i create the sprites and everything is working correctly.

**Comment by straker** [comment]
Awesome, glad it's working.
