### ISSUE TITLE
NPM warning during install, due to required NPM version being greater than 7.x

### ISSUE THREAD

**Issue by felladrin** [straker/kontra#310]
When using NPM v8+, `npm install` prints the following warning:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'kontra@8.0.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '<7.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.7.0', npm: '8.18.0' }
npm WARN EBADENGINE }
```

Maybe setting an explicit version range for NPM in `package.json` could solve it.

**Comment by straker** [comment]
Thanks for letting me know. I've gone ahead and removed the `npm` requirement. I had misunderstood what the `engines` property meant.
