### ISSUE TITLE
Allow Sprite to be a circle

### ISSUE THREAD

**Issue by straker** [straker/kontra#317]
If `radius` is passed to sprite, draw circle instead of square.

```js
Sprite({
  x: 0,
  y: 0,
  color: 'red',
  radius: 5
});
```

Additional this should allow collision detection between circle vs circle and circle vs square. Would also need to look through the code to see what other things may break / need to be updated to handle circles.

**Comment by crhallberg** [comment]
Would you expect x and y to be in the center of the circle or in the corner - which would allow rects and circles with the same x and y to occupy the same space?

**Comment by straker** [comment]
Ya. Ideally the sprites draw position would be the same regardless if it's a square or circle. A centered `anchor` property would draw both centered around the x/y position.
