### ISSUE TITLE
TileEngine camera centering and functionality

### ISSUE THREAD

**Issue by crimson-med** [straker/kontra#321]
I had a question on how does the `TileEngine.sx` renders for camera view?

I'm trying to create a camera that centers the player on the screen. In my update I used:

```
tileEngine.sx = character.x
tileEngine.sy = character.y
```

However it is not centering the player. (red) Furthermore it is also impacting the collisions as it offsets all the coordinates in some way.

Is it possible to get more insight on how the camera for the tileEngine works?

Video of the issue:

https://drive.google.com/file/d/1wUSULJRo881fX1H-BKy_-AoB6gq5Iypx/view?usp=sharing

As can be seen at the beginning the red character hits invisible wall which is actually the top of the left building. (big offset)

**Comment by straker** [comment]
The tileEngine sx/sy is the top-left corner of the tileEngine view, so if you set it to the character position it will try put the character to the top-left corner (if it can). You can see a full example of a centered player in the [camera tileEngine example](https://github.com/straker/kontra/blob/main/examples/tileEngine/camera/index.html).

For collision, which part is it impacting? If it's the player and the tile set, then you'll probably want to [add](https://straker.github.io/kontra/api/tileEngine#adding-objects-to-the-tilemap) the player to the tilemap. The example shows this as well.

**Comment by straker** [comment]
Going to close this as resolved. Feel free to reopen if your question wasn't answered.
