### ISSUE TITLE
[Doubt] How to play animations one after the other

### ISSUE THREAD

**Issue by 123survesh** [straker/kontra#325]
I have a simple scenario in mind, I have an idle animation and a kick animation. When I click on the kick button, the sprite has to play the kick animation and revert back to the idle animation.

Currently based on the docs, I was able to play the animation using *sprite.playAnimation('idle')*. Is there a way to detect the end of the animation? So that I can play the next animation and so on?

**Comment by straker** [comment]
That is a good question. I don't think there's anything that would let you know that automatically. For the time being, as long as the animation is not set up to [loop](https://straker.github.io/kontra/api/animation#loop) then in the `update` function of the sprite you can see if the animation has ended using some "private" properties of the animation:

```js
update() {
  // see if the animation has ended (_f is the current frame of the animation)
  if (this.currentAnimation._f === this.currentAnimation.frames.length - 1) {
    // play next animation
  }
}
```

**Comment by 123survesh** [comment]
One more question, why does **currentAnimation** object reflect the last played animation after it has been played, say in the case where **loop = false**? 
I felt it would be become null after the animation had finished playing, but if there is some reason behind it then having a simple flag like **isPlaying** in the **currentAnimation** object would be helpfull.

**Comment by straker** [comment]
No particular reason. `currentAnimation` is just the animation that was set to play. It doesn't currently clean itself up after the animation ends and just noops the animations update instead.

**Comment by straker** [comment]
Alright, with #335 merged the way to do this starting in the next release will be:

```js
if (this.currentAnimation.name === '<name>' && this.currentAnimation.isStopped) {
  this.playAnimation('<nextAnimation>');
}
```
