### ISSUE TITLE
How many sprites is too many?

### ISSUE THREAD

**Issue by tyfai** [straker/kontra#350]
Hi, I love your library and I'm using it to build a game!

The game is a tower defence style game and will have hundreds of sprites on screen at once. The canvas is 720x405.

Is it realistic to expect this engine to support that many sprites at once? A lot of them will be animated too if that makes a difference.

**Comment by straker** [comment]
Hard to say for certain. The [Object Pool example](https://straker.github.io/kontra/api/pool) has 1K+ nodes without any problems, but it does't use a lot of complex logic in how to move the sprites. When I was working on my [unfinished js13k game for last year](https://github.com/straker/js13k-2022/blob/main/src/index.js#L96) which uses steering behaviors for the enemy movement, I noticed the game slow down after about 500 or so enemies on the screen at a time.

**Comment by tyfai** [comment]
Thanks for sharing your experience. It's good to know a rough limit of 500 sprites at once.

I can see from your code that your game is running at 60 FPS (the default). Do you think halving the framerate to 30 FPS would allow for more sprites?

I guess it's not crazy to think that halving the framerate would double the performance. I think I'd rather have a playable 30 FPS tower defence game than a laggy 60 FPS one!

**Comment by tyfai** [comment]
Thanks for your insight. And thanks once again for releasing this library! :)
