### ISSUE TITLE
Render on whole pixels?

### ISSUE THREAD

**Issue by BinaryMoon** [straker/kontra#352]
Hi Kontra is great. I've been noodling with my first game with it and wondered if there was a way to render on whole pixels?

At the moment I have a scrolling background. It's 3 images lined up one after the other that loop as they go off screen. When I scroll on whole pixels it looks fine but if I use part pixels then I get gaps between the images.

So, is there a way to render images on whole pixels whilst keeping the physics (dx, dy) as floats? This would likely involve storing the render x and y separately, or rounding at draw time.

I was hoping the engine might have something that does this built in but I can't find it.

**Comment by straker** [comment]
Unfortunately there's nothing built into the library to enforce whole pixels. Kontra as a whole is a "basic" library in that it provides a framework for game objects but leaves most of the logic up to you.

**Comment by BinaryMoon** [comment]
No problem. Is there some way to hook into the render so I can do this myself? I couldn't see anything documented about this.

**Comment by straker** [comment]
Yep. For a Sprite you can pass a [render function](https://straker.github.io/kontra/api/sprite#custom-properties) when you create it to hook into the render function. The canvas will have been rotated and translated to the sprites position so {0,0} is the top-left corner of the sprite.
