### ISSUE TITLE
drotation

### ISSUE THREAD

**Issue by BinaryMoon** [straker/kontra#353]
Hi - I think it would be good to have a drotation property on game objects. This would function the same as dx and dy and allow for delta time updates automatically.

**Comment by straker** [comment]
Thanks for the suggestion. Could you elaborate more on what you mean by allowing delta time updates for dx and dy? Maybe some code examples of how you would want to use `drotation`?

**Comment by BinaryMoon** [comment]
Sorry - I probably confused things by mentioning them. When you use dx and dy it automatically applies a force to the x and y properties using delta time to get smooth motion at 60fps. I think the same thing for rotation would be useful.
