### ISSUE TITLE
Link to Web Maker broken

### ISSUE THREAD

**Issue by sylfel** [straker/kontra#354]
Hi

On homepage, in section [Web Maker](https://straker.github.io/kontra/getting-started#web-maker), webmaker website is broken
I don't know if it's "normal" (i think no) and there's a certificate problem, so it may be dangerous.

Maybe this section can be dropped ?

**Comment by straker** [comment]
Thanks for letting me know. Looks like the url changed and is now https://webmaker.app/. I'll update the docs for the next release.

**Comment by straker** [comment]
Closed via #358
