### ISSUE TITLE
TileEngine and Pointer Click

### ISSUE THREAD

**Issue by sylfel** [straker/kontra#355]
Hi,

I try to intercept click on tileEngine and get row/col from pointer information
track tileEngine is not possible, because tileEngine define a _r function

So, what is the best way to get row/col from pointer click ?

**Comment by straker** [comment]
Good question. TileEngine doesn't really have anything to turn x/y coords into row/col coords. You could borrow [the two functions](https://github.com/straker/kontra/blob/main/src/tileEngine.js#L6-L30) to do that and then on click pass them the pointer x/y coords and the tile width/height to get back row/col.

```js
function getRow(y, tileheight) {
  return (y / tileheight) | 0;
}

/**
 * Get the col from the x coordinate.
 * @private
 *
 * @param {Number} x - X coordinate.
 * @param {Number} tilewidth - Width of a single tile (in pixels).
 *
 * @return {Number}
 */
function getCol(x, tilewidth) {
  return (x / tilewidth) | 0;
}
```
