### ISSUE TITLE
Allow `randInt` to accept a seeded random object

### ISSUE THREAD

**Issue by straker** [straker/kontra#377]
It would be nice if `randInt` could take a seeded random generator to produce the random int. Maybe `randInt(min, max, seed = Math.random)`?

**Comment by straker** [comment]
Instead of allowing `randInt` to take the seeded random number, I think the `seedRand` should be reworked to have a `randInt` function in conjunction to [saving/loading the seed](#374).

**Comment by sylfel** [comment]
Hello straker

Is "seedRand"  may be transform into a class with some functionnality ? (load/save seed, randInt, randFloat, bias parameter...)
Or do you think it must be still a function to preserve compatibility ?

**Comment by straker** [comment]
My current line of thinking is to rework the function and turn it into an object with properties (not so much a class). Similar to what I did in my [js13k game from last year](https://github.com/straker/js13k-2023/blob/main/src/utils.js#L145-L169). I haven't thought much about it though, so that could very well change when I start to do the work.
