### ISSUE TITLE
[feature request] Pixi.js

### ISSUE THREAD

**Issue by FreeSolDev** [straker/kontra#382]
Would love to see Pixi.js implemented,Recent v8 Pixi to be exact,it supports webgpu and has fallback for webgl utilizing the same api

**Comment by straker** [comment]
Thanks for the request. Unfortunately implementing Pixi.js into Kontra.js is beyond the scope of this project. Kontra.js is just a simple framework to use that is intended to plug-and-play into other libraries or frameworks if you want more than the basic functionality. Not only that, but the entire Pixi.js library is twice the size of Kontra.js which would make it really difficult to use in js13k.
