### ISSUE TITLE
Simple game sample - 

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#40]
I made a slide puzzle using kontra. Here's the code:

https://github.com/boldbigflank/kontra-samples

and the demo:

http://alexswan.info/kontra-samples/

I might do a write up later, with a step by step, but it's good to peek at now.

**Comment by BoldBigflank** [comment]
I've been working on this, adding more demos to this repository. I'm gonna have to rename it so it's more fitting.
I just added a simple Hundreds clone : http://alexswan.info/slidepuzzle/hundreds.html
I'm pretty proud of implementing circle collision physics in that one.

**Comment by BoldBigflank** [comment]
I added a few more examples and changed the repo name, and updated the original post with the new links.

**Comment by straker** [comment]
Sorry it took a bit, but I finally added them to the Games Made with Kontra section of the docs.

I love what you're doing and seeing all the awesome games. Keep up the good work!
