### ISSUE TITLE
Download page links version with broken animations

### ISSUE THREAD

**Issue by crabcode** [straker/kontra#415]
Just found myself stuck a while trying to figure out how to get animations to work, until I noticed the samples don't work either. Turns out there's an issue with version 10.0.0 that seems to have started in 9.1.0, where only ever the first frame of the spritesheet is rendered, even if it isn't included in `animation.frames`

Switching to 10.0.1 or .2 solves the problem, so the bug seems fixed already, but the Download page still lists CDN links for the 10.0.0 version, which is how I ended up with it, so updating that to the latest might save another clueless soul an hour or two of confusion ;)

(Edit: Download, not Getting Started)

**Comment by straker** [comment]
Pages updated with latest version.
