### ISSUE TITLE
More collisions

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#44]
I've been thinking of a few ways to make more robust collision detection. Perhaps it should be its own plugin. It'd be nice to say what shape it is, then let the plugin decide what algorithm to do.

```
collidesWith: kontra.collisions.circle
```

**Comment by straker** [comment]
Thanks for the idea. I'm kinda hesitant to add robust collision detection as it would start to creep into 2D physics engine territory. I've also not done any type of collision outside simple square/circle shapes, so wouldn't know how to do more types than just that.

However, if we wanted to just limit it to square and circle shapes (square vs square, square vs circle, circle vs circle), with the capacity to expand it to add more types or change the collision algorithm (the default being AABB), I could get behind that.

**Comment by straker** [comment]
So I've been thinking about this more recently, and I wanted to get your input on it before moving forward.

The api for a collision plugin seems a bit clunky out of the box. What I mean is let's say the plugin defined 2 shapes: `rectangle` and `circle`, and provided 3 functions for how those 2 shapes could collide: `rectVsRect`, `rectVsCric`, and `circVsCirc`. It might also provide an interface to abstract that so you wouldn't have to determine which one to use on the sprite, say `collidesWith`.

To use this plugin, what you would need to do is override the sprites collision with the plugin ones manually: `kontra.sprite.prototype.collidesWith = kontra.collisions.collidesWith`, then you could create sprites with `shape` properties of `rectangle` or `circle`. and the collision would sort itself out.

It's the overriding manually part that's a bit clunky. It'd be better if it did that out of the box, sort of like upgrading the Sprite. But I try to keep a "as little interdependency" requirement as possible (pointer has caused some issues with that). 

So this sparked in interested idea: what if Kontra supported a plugin ecosystem. Wouldn't it be awesome if js13k participants created small snippets of code that could plug into the Kontra framework and added functionality that other participants could use? Could you imagine if Xem's amazing [mini 2D physics engine](https://twitter.com/MaximeEuziere/status/1084389400967086080) could be added into Kontra if you needed it and then all sprites automatically had a physics engine behind them?

We could create a few examples, collision being one of them, then add links to any others people create. Make it super nice to start a new game and be able to bring in more things you need.

Doing this would probably increase the size of the library a bit as I would add support for lifecycle events (similar to `kontra._init()` and `kontra._tick()`) and other things like managing multiple plugins trying to override the same function.

Anyway, what do you think?
