### ISSUE TITLE
Object Pool always making object to maxSize

### ISSUE THREAD

**Issue by parkercouch** [straker/kontra#47]
When getting objects from an object pool the get() method will check current objects and always find that to be true when using kontra.sprite as the create property (kontra.sprite init defaults to ttl=Infinity). In my own project I just changed the default to 0 and specify Infinity on non-pool sprites to get around the issue. Not sure if there is a better way to fix this. I noticed it when I didn't set a max size and my browser tab stopped responding (it was stuck in an infinite loop of object creation). 

This test will fail. The other pool tests use a modified sprite which doesn't include ttl.
```js
    it('should not continue making objects if not needed', function() {
      var pool = kontra.pool({
        create: kontra.sprite,
        maxSize: 500
      });

      for (var i = 0; i < 129; i++) {
        pool.get();
      }

      expect(pool.size).to.not.equal(pool.maxSize);
      expect(pool.size).to.be.equal(256);
    });
```

**Comment by straker** [comment]
That's what I get for not using a true sprite in the test. Thanks for finding this.
