### ISSUE TITLE
Pointer doesn't work past bottom of the page

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#50]
This one took a while to figure out. I have a canvas that is under a list of players. When two or more people were joined in a game I'm making, the a tracked sprite being used as a Start button wouldn't work sometimes. Found out it was only when I had to scroll down to hit the button because it was under the fold.

**Comment by BoldBigflank** [comment]
I'm not able to reproduce in a simpler sample, but I do have a PR that should fix it. This is based off of my drawing controls for Jackbox Games (Drawful, Tee KO, etc)

**Comment by BoldBigflank** [comment]
https://github.com/straker/kontra/pull/51

**Comment by straker** [comment]
Closed vi #51
