### ISSUE TITLE
Asset Loading - loading multiple times

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#55]
Would it make sense for the `kontra.assets.loadImage` function to resolve with the existing image if it has already been loaded into the `assets`? Same with the other load functions.

**Comment by straker** [comment]
Good question. I don't see any reason why it wouldn't hurt. Is there a use case where you're setting the image from the load function return rather than through `kontra.assets.images[name]`? 

I just realized that isn't documented in the docs, should probably update that.

**Comment by BoldBigflank** [comment]
Yeah, the way I'm setting up my games is it has a reset function, which loads the assets, and in the return creates new sprites. I'd like to let this function be smart enough to use existing image assets if they are already in memory, rather than loading new Images every time.
