### ISSUE TITLE
Sprite - Find What Animation is playing

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#59]
there's `playAnimation` but not something like `currentAnimation` that returns the name of the animation the current frame is showing, ie 'walk'

**Comment by straker** [comment]
[Prior to 4.0.0](https://github.com/straker/kontra/releases/tag/v4.0.0) there was a `currentAnimation` property, but I couldn't think of a use case to have it so made it private instead to save bytes. If you have a compelling reason to look at the currently playing animation I could bring it back to the public light.

**Comment by BoldBigflank** [comment]
It would come in handy for the way I'm using spritesheet animations, which is kind of not how it is intended. I'm using a single sprite sheet for all my sprites, and each 'animation' is one non-looping frame (`playAnimation('captain-blue)`). Getting the current animation is a way of answering "what am I?"
