### ISSUE TITLE
Sharing my Kontra tutorial

### ISSUE THREAD

**Issue by fariazz** [straker/kontra#6]
Hi @straker , just wanted to share my tutorial on how to make a simple game with the Kontra library for the js13kgames competition: https://www.youtube.com/playlist?list=PLnEt5PBXuAmth8WkrrbUxXoERdjovZYdR

Do you think you can add it to a Resources section in the readme? (I can do it and do a pull request if you want)

**Comment by straker** [comment]
Thanks for the video tutorial, it was fantastic! I'd love a link in the readme, please do add a pull request adding a Resources section and link and I'll get it merge.

Thanks for also showing were my docs were lacking in features so I can improve them (like how to actually load a Tiled map).

**Comment by fariazz** [comment]
Thanks @straker , glad to hear you liked it! Hope it can get more people to use this framework for js13kgames and game prototyping in general, I had a good time making it.
