### ISSUE TITLE
Multiple sprites using the same animation multiplies the framerate

### ISSUE THREAD

**Issue by BoldBigflank** [straker/kontra#60]
I have 3 sprites playing the "skeleton" animation, and they are playing their animation at 3x speed. When there's 2, it goes 2x, etc. Seems the animation data is being shared and the update function is being called for each.

**Comment by straker** [comment]
Odd. How are you sharing the animation? `kontra.sprite` should clone the animation when created https://github.com/straker/kontra/blob/master/src/sprite.js#L152-L159. Though looking at the code I wonder if line 159 is assigning the `firstAnimation` to a non-cloned version and thus sharing accidentally.

**Comment by straker** [comment]
And a quick test shows that the first animation is indeed not cloned due to that line.

**Comment by straker** [comment]
Scratch that, the test was mocking `animation.clone` so it should be cloning properly in the sprite.

**Comment by BoldBigflank** [comment]
Here's a way to reproduce it.
https://jsfiddle.net/fav1rjn8/1/
in this fiddle, on line 39 I'm setting the animations right there. Guess I gotta clone them then?

**Comment by straker** [comment]
Let me know if the latest version doesn't fix the problem.

**Comment by BoldBigflank** [comment]
Problem still exists. You can see in this fiddle:
https://jsfiddle.net/b6v1wtmn/8/
change the top line to a number to make it go real fast.

**Comment by straker** [comment]
Ah, I see. You're assigning the animation object to each sprite directly. Yes that would cause them all to share all animations. If instead you pass `kontra.sprite` an [animations property](https://straker.github.io/kontra/api/sprite#animation-sprite), then the sprite will clone all the animations for you so they don't share.

```js
let sprite = {
    width: 72 * 2,
    height: 97 * 2,
    anchor: {
      x: 0.5,
      y: 0.5,
    },
    x: 300,
    y: 200,
    animations: spriteSheet.animations
  }

  // pass the animations to the sprite
  window.sprites = []
  for (let i = 0; i < SPRITE_COUNT; i++) {
    let s = kontra.sprite(sprite)
    s.x += i * s.width
    s.playAnimation('walk')
    window.sprites.push(s)
  }
```

**Comment by BoldBigflank** [comment]
The reason I'm assigning the animation object afterwards is because I'm defining the sprites I use beforehand, then on loading/resetting I'm loading the spritesheet images and creating the game sprites.

**Comment by BoldBigflank** [comment]
Ok, so would it make sense to add a `setAnimations()` function to Sprite, so I can use it to get a fresh copy when I assign it later?

**Comment by straker** [comment]
Possibly. I'm wondering if I should must make `animations` a setter and then auto clone there since that's pretty important to making it work correctly.

**Comment by BoldBigflank** [comment]
Yeah, that's what I'm trying. I can send a PR.
