### ISSUE TITLE
Broken links on docs

### ISSUE THREAD

**Issue by michaelauderer** [straker/kontra#74]
On the docs, all links are broken and take you back to the homepage.

**Comment by michaelauderer** [comment]
You can assign this to me :)

**Comment by straker** [comment]
Dang it. Trying to get the docs to work locally and when deployed to github pages is a bit of a hassle.

**Comment by michaelauderer** [comment]
I'm a bit stuck on this, I tried a few solutions but none work right. The problem seems to be caused by the <base> tag. Maybe previously the pages were at the root, but now they're under the /api subdirectory so that's why the links are broken.. but updating the generated URLs to the new /api format seems beyond my knowledge of handlebars.

**Comment by straker** [comment]
It probably has more to do with the fact that I'm greatly abusing what LivingCSS was meant to do. 

As it stands, only api pages use the table of contents and links for headings. We could just change all hrefs that use `#{{ name }}` and `#{{ link }}` to assume the /api route and use the name of the page, which comes from the topmost `id` property of the context (generated from LivingCSS). So something like `api/{{ ../id }}#{{ name }}` (or `link`).
