### ISSUE TITLE
Asset loading progress

### ISSUE THREAD

**Issue by wini3d** [straker/kontra#84]
I noticed this was removed when the [asset loader](https://github.com/straker/kontra-asset-loader) was merged, what is the alternative when showing or notifying progress?

**Comment by straker** [comment]
Unfortunately Promises no longer have a `notify` function (the angular promise polyfill I was using did). So there's not really a way to notify though the functions when an asset has loaded other than calling some global function.

Now that I think about it, I could add a notify event using the recently implemented [events api](https://straker.github.io/kontra/api/events).

**Comment by wini3d** [comment]
I see and that would be great if loading progress can be tied to events. Looking forward to it.

btw, something that I found recently without the `notify` function that might be of use as well..
https://codepen.io/potch/details/yereOM
