### ISSUE TITLE
Getting Player coordinates/position on tileEngine map?

### ISSUE THREAD

**Issue by wini3d** [straker/kontra#88]
How to get the actual player x and y position relative to the tileEngine map?

**Comment by straker** [comment]
If you're using using `sx` and `sy` to change the camera, then you'll need to add those to the `x` and `y` position of the player.  

```js
const x = tileEngine.sx + player.x;
const y = tileEngine.sy + player.y;
```

**Comment by wini3d** [comment]
Thanks, works great :+1:
