### ISSUE TITLE
Dynamic sprite/object placement on tileEngine map

### ISSUE THREAD

**Issue by wini3d** [straker/kontra#89]
I'm trying to add some static and dynamic sprites to a tileEngine level, having x and y properties with a value of 0 sticks it to the top left of the screen and just follows the player.

So how do you place sprites on specific location or parts of the level? This is somehow related to my last closed issue. Thanks.

**Comment by Rayne** [comment]
I am currently adding `sx` and `sy` to sprite cordinates before rendering them. Afterwards the old values have to be restored. I'm thinking about writing a plugin which adds a `renderSpritesInTileWorld` function if there is no better solution. I'm also using a custom `getCol` and `getRow` function which ignores `sx` and `sy` to be able to handle collisions between Sprites "placed in the tile world" and tiles.

**Comment by straker** [comment]
Sorry, I'm not sure I completely follow so I apologize if this doesn't answer the question. 

The TileEngine essentially acts as a background image. It only knows how to crop a large map at the specific `sx` and `sy` points and draw it to the size of the canvas. Sprites don't have any knowledge about the TileMap and so just draw at their `x` and `y` position. This is why in the TileMap example when the player is "moving" it's really the TileMap that is moving. Once the player is near the edges of the TileMap the player starts moving and the TileMap doesn't.

With that in mind, you'll need each Sprite to draw at its relative position instead of its true position. If you don't mind hacking the library (I don't) and how much the Sprites know about the TileEngine you can do something like this:

```js
const tileEngine = TileEngine(/* ... */);

// change x and y to account for the position of the TileEngine
Object.defineProperties(kontra.Sprite.prototype, {
  x: {
    get() {
      return this.position.x - tileEngine.sx;
    }
  },
  y: {
    get() {
      return this.position.y - tileEngine.sy;
    }
  }
});
```

That should then let the Sprite draw correctly to the TileEngine world so long as `x` and `y` are its true position.

**Comment by straker** [comment]
Thinking about this some more, I could see the TileEngine having a function that smooths this over a bit so drawing objects to their relative or true position is easier.

**Comment by Rayne** [comment]
Doesn't this modification introduce problems with the `layerCollidesWith` function (which is using `getRow` and `getCol`)?

My workaround for rendering sprites:

```javascript
/**
 * Kontra's TileEngine doesn't handle sprites.
 * Therefore rendering a sprite doesn't place the sprite inside the tile world
 * but relative to the view port of the canvas.
 * This method renders the sprite on the correct position in the tile world.
 */
renderSpriteGlobally(sprite) {
    sprite.x -= this.engine.sx;
    sprite.y -= this.engine.sy;

    sprite.render();

    sprite.x += this.engine.sx;
    sprite.y += this.engine.sy;
}
```

**Comment by straker** [comment]
Ah dang, you're right. `layerCollidesWith` expects x and y to be true position...

**Comment by wini3d** [comment]
Thanks guys. works perfectly now. It seems this also introduces collision problems and render order though the rendering order is more game specific and should be just render the sprite that is on the top to bottom for the example, if I'm not mistaken.

>I'm also using a custom `getCol` and `getRow` function which ignores `sx` and `sy` to be able to handle collisions between Sprites "placed in the tile world" and tiles.

@Rayne That's nice and would be interested to know how to achieve this with sprites besides the player and the collision tiles. 

@straker Any chance of an update where a sprite to sprite and other sprites to tile will have simple placement/movement and collision checking when using the tileEngine?

**Comment by straker** [comment]
@wini3d Yep. Should be able to get something out soon. Just need to figure out how I want to handle it.

**Comment by Rayne** [comment]
@wini3d I have uploaded and documented my helper class: [tile-engine-collisions](https://github.com/Rayne/kontra-prototype/tree/master/tile-engine-collisions). I assume that a shorter solution with a better API is possible but I had not enough time to think about it.

**Comment by straker** [comment]
Alright, new version has the fix. You can now add objects to the tileEngine and the x,y position will be the location in the tile map. The sprite will take care of drawing at the correct spot on the canvas based on the tile engine camera.

The tile engine example has all the updated code.

```js
let sprite = Sprite({
  x: 100,
  y: 100
});

let tileEngine = TileEngine({/*...*/});
tileEngine.add(sprite);

// now when you render the sprite, it will be on the tile map at position {100,100} and draw properly based on the camera
sprite.render();
```
