### ISSUE TITLE
Is kontra.assets.loadImage() deprecated?

### ISSUE THREAD

**Issue by panphora** [straker/kontra#9]
First of all, amazing framework! I plan to use it to teach a class on JavaScript to people who are new to coding.

Anyways, I was trying to run some of the examples and I got the error `kontra.assets.loadImage is not a function` a couple times. However, when I replaced the call with `kontra.assets.load` everything worked!

I'm pretty sure it's because the API changed at some point, but I couldn't find any mention of it.

**Comment by straker** [comment]
Thanks for the kind remarks. And yes, sorry, `kontra.loadAssets` was deprecated in favor of using `konra.assets.load`. I was in such a rush to get the next version out for js13k that I didn't make great release notes. Let me do so now in the 3.0 release.

**Comment by straker** [comment]
Alright, added the very long list of deprecations. Hopefully that clears things up.
