### ISSUE TITLE
TileEngine.setTileAtLayer() is expensive by immediately calling prerender()

### ISSUE THREAD

**Issue by Rayne** [straker/kontra#90]
`TileEngine.setTileAtLayer()` is an expensive function because it is immediately calling `prerender()`. This can lead to performance problems, e.g. when updating 10x10 tiles (100 x `prerender()`) in one frame.

**Comment by straker** [comment]
You're right. I think what I'll do is set a `dirty` flag on the TileEngine if tiles have been dynamically set and then call `prerender` before `render` when dirty. That should let you do batch changes and only call `prerender` once.
