### ISSUE TITLE
Suggestion: Sprite Z Ordering Feature

### ISSUE THREAD

**Issue by wini3d** [straker/kontra#94]
It would be nice to easily have a sprite z ordering feature (with options) particularly with the tileEngine in addition to the position all sprites including player controlled sprite.

An example option would be basing it on y value for top down maps.

**Comment by straker** [comment]
If I understand correctly, you'd like something like this?

```js
spriteManager = new SpriteManager();

/* add all sprites to spriteManager */

// somewhere else in the code
sprite.z = 10;

loop = new GameLoop({
  render() {
    spriteManager.render(); // renders all sprites in z order (or y order)
  }
});
```

**Comment by wini3d** [comment]
Yes, would it also be nice to automatically set the sprite z property?

example:
`spriteManager.renderY()` 
..or renderX() if this is also used on some type of games.

so for top down styles like the tileEngine example it automatically sets all the sprites ordering depending on the sprites y location and perhaps you can set the others manually or exclude them on conditions like a gui sprite that is always rendered last.

**Comment by ajbkr** [comment]
I too would find this a useful addition, especially where the "z index" of a sprite can be set based on the sprite's `y` property but that also takes the `anchor.y` property into consideration.

**Comment by sdfereday** [comment]
I ended up doing something like this (seems to work):

    render:() => {
      tileEngine.render()
      sprites
        .sort((a, b) => Math.round(a.y) - Math.round(b.y))
        .forEach(sprite => sprite.render());
    }

I'm sure there's a more elgant solution out there but just in case it's any use for folk.
