### ISSUE TITLE
Collision direction and blocking sprites

### ISSUE THREAD

**Issue by wini3d** [straker/kontra#99]
How do you detect the direction of collision? I tried updating the collision with the code below to move the chicken, but can be stopped in any direction by the player.

```
    window.chicken = kontra.Sprite({
        x: tileEngine.sx + 400,
        y: tileEngine.sy + 50,
        count: 0,
        animations: chickenSpritesheet.animations,
        update: function() {
            if (!this.collidesWith(window.collisionBox)) {
                this.x = this.x + .5
            }
            this.advance();
        }
    });
```

Also, would it also be possible to have the same collision effect as the tile collision layer and player, between sprites? sort of sliding effect or free movement if the other entity or sprite is standing beside the player or any sprite.  An example would be if the player presses against any side of the bridge and can still move up or down freely. just curious.

**Comment by straker** [comment]
The tileEngine doesn't really have any different collision detection than the sprite. The example uses a collision box to project where the player will be after an update to see if the player can do so. You can do something similar with the chicken so it doesn't get "stuck" against a collision.

```js
update: function() {
  const prevX = this.x;
  this.x = this.x + .5;
 
  if (this.collidesWith(window.collisionBox)) {
    this.x = prevX;
  }
}
```

**Comment by wini3d** [comment]
Thanks, it did solve the problem being stuck. How about handling collision by direction?

**Comment by straker** [comment]
The library doesn't have anything to detect the direction of the collision. You might try advancing each direction individually and see which direction collides first.

**Comment by wini3d** [comment]
I see, but this already works on the tile collision layer vs player?

**Comment by straker** [comment]
Only because the example code checks each individual direction first for collision:

```js
if (kontra.keyPressed('up')) {
  // check collision and advance
}
else if (kontra.keyPressed('down')) {
  // check collision and advance
}
else if (kontra.keyPressed('left')) {
  // check collision and advance
}
else if (kontra.keyPressed('right')) {
  // check collision and advance
}
```

**Comment by wini3d** [comment]
I see. Perhaps this is more of a Sprite class issue and a feature request. Here's exactly what I was hoping for that I saw in this playable js rpg demo:

https://thenyanta.github.io/JS-RPG-Engine/

If you block the dog in front, he stops moving, but still continues to run when you bump him on the side while running. I think something like this should be built-in or added within the collision system.

**Comment by straker** [comment]
There was talk of a more [advance collision detection system](https://github.com/straker/kontra/issues/44), but it wasn't something I really wanted to add to the library as I like to keep it small and focused.

**Comment by wini3d** [comment]
Great! That would be awesome to have as a plugin instead.
